### ISSUE TITLE
Architecture proposal for hooking up media processing

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/VideoDeduplication#220]
Once we have the skeleton UI #199 hooked up, we need to actually allow for processing of media files.

For this task the end goal is to:

* allow users to provide files to be processed by the machine learning algorithm via the front end

* it should allow a user to provide a single file, directory, or txt list of file locations (as is currently supported for the processing scripts)

* for right now we can enforce that these files must come from the attached data drive (so we wont actually be handling real 'uploads'. As a result we almost certainly can't use the default OS file explorer and may have to custom render a view of the files we can access. txt file content may just be pasted directly into an entry form

* once the file(s) are provided, we should be able to give some indication of processing status - probably binary at first (in progress, done) but could be cool in the future to have some real time % progress (even just at the job level)

* once the processing has been completed, the expectation would be that those videos would be available in the grid view

One big outstanding question is how matching should be handled. For example, if a user has previously processed and matched 1 million files - then later add 1 incremental file - how do we ensure the matches are updated to include the incremental file (hopefully as efficiently as possible)

**Comment by stepan-anokhin** [comment]
## Requirements

It would be helpful for me to split the requirements into smaller pieces in more implementation-oriented way. 

Here is how I see it: 
1. User can submit tasks via frontend. 
2. User can see list of submitted tasks with their current status: `PENDING`, `PROGRESS`, `SUCCESS`, `FAILURE`, `CANCELLED`.
3. User can cancel tasks and/or delete them from the list. 
4. User can see progress of each particular task in % (with progress bar).
5. Task status and progress are updated dynamically, page reload is not required.
6. User can see logs of finished tasks via frontend.  
7. User can see logs of tasks in progress dynamically via frontend, as they generated. 

In my understanding 1-4 are must-have, 5 is highly desirable for better UX, 6-7 are rather optional 
(nice to have, especially for debugging purpose, but should be done after 1-5). 

@johnhbenetech please let me know if you think this list should be changed.
It is more backend-oriented, I didn't put a lot of thoughts into frontend UX/layout 
(especially about how user will pick individual files/directories or preview selected file list).
Currently I assume we can start from [this mockup](https://projects.invisionapp.com/share/3ZWKQY354PN#/screens/412274155)
(as we discussed) and change it or add more views as necessary.

## Backend Changes 

Changes required to implement 1-3 (ETA 3d):
* Deploy a Celery worker in the `dedup-app` container (or in separate container if it's not possible). The Celery worker will receive tasks and invoke pipeline accordingly.
* Deploy a message broker in a separate container. It could be Redis or RabbitMQ. Redis looks good as it could also be used to store task statuses (Celery supports it out of the box).
* Add a new server endpoint for tasks (e.g. `/api/v1/tasks`):
  * `POST /tasks` - create a new task. Return task details (including task id) as a JSON.
  * `GET /tasks` - get task list.  
  * `GET /tasks/<id>` - get individual task
  * `DELETE /tasks/<id>` - terminate task and delete it from the list. 
  * `PATCH /tasks/<id>` with `{"status": "CANCELLED"}` payload - cancel the task (for all other payloads should return `400`) 
* Probably we will also need a new endpoint to query all files from the data-folder (including non-processed ones). @johnhbenetech we should decide how the file-selection workflow will look like and then revisit this item.  

Some implementation notes for 1-3:
* Once task is posted the server will send a request to the Celery worker (via broker) and return a new task details (using `AsyncResult` object, returned by Celery client).
* To get a complete list of active and finished tasks we can query from Celery's [result backend](https://docs.celeryproject.org/en/stable/userguide/tasks.html#result-backends) of our choice. If we're not going to keep task history for extended period of time, then I think Redis should be good for this purpose as it could be used both as a broker and as a result backend. 
* Task cancellation is straight forward: create `AsyncResult("task-id")` by task id and then call `revoke(terminate=True)`.

Changes required to implement 4 (ETA <1d):
* Refactor existing pipeline to be able to publish current progress dynamically. The client code should be able to register a listeners for progress updates or alternatively for specific events (e.g. "file list is formed", "file features are extracted"). This is a relatively minor change.
* Celery worker will register it's listeners to publish progress metadata to result backend (e.g. `self.update_state(state='PROGRESS', meta={'current': i, 'total': len(files)})`, see [Custom States](https://docs.celeryproject.org/en/latest/userguide/tasks.html#custom-states) for details).
* API Server will query result backend and get progress from saved state metadata.

Changes required to implement 5 (ETA 1-2d):
* If we choose Redis as a result backend then server will subscribe for task updates. 
* When user opens a page with task list the frontend will connect to the server with SocketIO (or bare WebSocket) and receive updates dynamically.
* Add [Flask-SocketIO](https://flask-socketio.readthedocs.io/en/latest/) handlers to send dynamic status updates. 

Changes required to implement 6 (ETA 1-2d):
* Configure Celery task logger so that each task will write logs to a separate file. There are various ways to implement that (e.g. via custom task base class). 
* The task log-files could be stored on mounted data-folder or on dedicated volume (mounted to `dedup-app` and  `server` containers).
* Add `GET /api/v1/tasks/<id>/log` method that will return task logs. Server should be able to figure out log-file name by task id (it could be a pattern or specific metadata in Celery result backend). 

Changes required to implement 7 (ETA 1-2d):
* When task status is `PROGRESS` and user opens task's logs view instead of issuing `GET /api/v1/tasks/<id>/logs` request the frontend subscribes to the log updates via SocketIO and display them dynamically.
* When frontend is subscribed to the log updates the `server` must receive and publish task logs accordingly. It could be implemented in various ways:
  * by emulating `tail -f` on task log file
  * by subscribing to specific events via message broker (we can use Redis PUB/SUB for that).

## Frontend Changes

TBD.

@johnhbenetech I think we should decide how the file-selection should be done on frontend. Some backend changes depend on this. 

But we can definitely start from something very simple (like manual writing single file path). 
The task list could be exactly like in [the mockup](https://projects.invisionapp.com/share/3ZWKQY354PN#/screens/412274155).

If we decide to display logs there should be dedicated view for that as well.
